---

- name: Reboot Server
  hosts: "{{ hosts | default('') }}"
  gather_facts: false

  vars:
    reboot_timeout: 300

  tasks:
    - name: Check server connectivity
      timeout: 5
      ansible.builtin.ping:

    - name: Reboot server
      timeout: "{{ reboot_timeout }}"
      ansible.builtin.reboot:
        test_command: hostnamectl
