---

- name: Refresh Package Cache
  hosts: "{{ host_limit | default(omit) }}"
  gather_facts: false

  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset: ['min']

    - name: Clear package manager cache
      ansible.builtin.include_role:
        name: pkg-mgmt
        tasks_from: clear-cache

    - name: Update package manager cache
      ansible.builtin.include_role:
        name: pkg-mgmt
        tasks_from: update-cache
