---

# 1 = Server needs reboot
# 0 = Server does not need a reboot
- name: dnf-needs-restarting | Check if system needs a reboot
  register: _patching_requires_reboot
  changed_when: false
  failed_when: false
  ansible.builtin.command: dnf needs-restarting -r

- name: dnf-needs-restarting | Set flag to restart server
  when: _patching_requires_reboot.rc == 1
  ansible.builtin.set_fact:
    patching_restart_server: true
