---

- name: User Account Setup
  hosts: all
  gather_facts: false
  roles:
    - role: users


- name: Server Setup
  hosts: all
  gather_facts: true

  tasks:
    - name: Apply simple hardening to ssh
      ansible.builtin.include_role:
        name: devsec.hardening.ssh_hardening

    - name: Run any handlers before proceeding
      ansible.builtin.meta: flush_handlers

    - name: Remove any root user password
      become: true
      changed_when: true
      ansible.builtin.command:
        cmd: passwd -d root

    - name: Apply any updates to the server
      ansible.builtin.include_role:
        name: patching

    - name: Reboot the server (if required)
      when:
        - patching_restart_server is defined
        - patching_restart_server
      ansible.builtin.reboot:
        test_command: ping -c 1 1.1.1.1
