---

- name: Fact Gathering
  hosts: all
  strategy: free
  gather_facts: false

  tasks:
    - name: Get general system facts
      ansible.builtin.setup:
        gather_timeout: 30
        gather_subset:
          - 'min'

    - name: Get system service facts
      ansible.builtin.service_facts:

    - name: Group hosts by os-family
      ansible.builtin.group_by:
        key: os_{{ ansible_os_family }}


- name: User Account Setup
  hosts: all
  gather_facts: false
  roles:
    - role: users


- name: Server Setup
  hosts: os_RedHat
  gather_facts: false

  pre_tasks:
    # im including this step here just for documentation purposes
    # most development occurred inside container where a lot of
    # packages were missing. So I want to run a series of tasks prior
    # to doing any "real" work
    - name: Run baseline role against server
      ansible.builtin.include_role:
        name: baseline

  tasks:
    - name: Apply simple hardening to ssh
      when:
        - ansible_facts['services']['sshd.service'] is defined
        - ansible_facts['services']['sshd.service']['state'] == "running" | default(False)
      ansible.builtin.include_role:
        name: devsec.hardening.ssh_hardening

    - name: Run any handlers before proceeding
      ansible.builtin.meta: flush_handlers

    - name: Remove any root user password
      become: true
      changed_when: true
      ansible.builtin.command:
        cmd: passwd -d root

    - name: Apply any updates to the server
      ansible.builtin.include_role:
        name: patching

    - name: Reboot the server (if required)
      when:
        - patching_restart_server is defined
        - patching_restart_server
      ansible.builtin.reboot:
        test_command: ping -c 1 1.1.1.1
