---

- name: Password Update Playbook
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Update ansible_user account
      loop: "{{ users_accounts }}"
      when: 'item.name in ansible_user and item.password'
      no_log: "{{ nolog | default(True) }}"
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash }}"

    - name: Update the ansible_become_pass when password_override is set
      no_log: "{{ nolog | default(True) }}"
      when: 'password_override is defined and password_override'
      ansible.builtin.set_fact:
        ansible_become_password: "{{ password_override }}"

    - name: Update account information
      loop: "{{ users_accounts }}"
      no_log: "{{ nolog | default(True) }}"
      when: 'item.name not in ansible_user and item.password'
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash }}"
