---
version: 3

build_arg_defaults: {}

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: []
  python:
    - yt-dlp
  system:
    - git [platform:rpm]
    - ffmpeg-free [platform:rpm]

images:
  base_image:
    name: registry.fedoraproject.org/fedora:39
    # Other available base images:
    #   - quay.io/rockylinux/rockylinux:9
    #   - quay.io/centos/centos:stream9
    #   - registry.fedoraproject.org/fedora:38
    #   - registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest
    #     (needs an account)

# Custom package manager path for the RHEL based images
# options:
#  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: scripts
    dest: ee_scripts

additional_build_steps:
  append_final:
    - COPY _build/ee_scripts/install-tools.sh /usr/local/sbin/
    - RUN sh /usr/local/sbin/install-tools.sh